apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: azure-runners
  namespace: btns
spec:
  replicas: 0
  template:
    spec:
      organization: beartoucan
      labels:
        - btns
        - azure
      env:
      - name: RUNNER_FEATURE_FLAG_EPHEMERAL
        value: "true"
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: azure-runners-deployment-autoscaler
  namespace: btns
spec:
  scaleTargetRef:
    name: azure-runners
  minReplicas: 0
  maxReplicas: 3
  scaleUpTriggers:
  - githubEvent: 
      workflowJob: {}
    amount: 1
    duration: "5m"
